### ISSUE TITLE
Incompatibility with stdlib 4.16.0

### ISSUE THREAD

**Issue by concon121** [artberri/puppet-nvm#16]
Installing puppet-nvm via Vagrant i'm getting the following error:

```
 Error: /Stage[main]/Nvm/File_line[add NVM_DIR to profile file]: Could not evaluate: can't convert Hash into String
==> VerticalServer: /etc/puppet/modules/stdlib/lib/puppet/provider/file_line/ruby.rb:43:in `readlines'
==> VerticalServer: /etc/puppet/modules/stdlib/lib/puppet/provider/file_line/ruby.rb:43:in `lines'
==> VerticalServer: /etc/puppet/modules/stdlib/lib/puppet/provider/file_line/ruby.rb:6:in `exists?'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/property/ensure.rb:81:in `retrieve'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/type.rb:1035:in `retrieve'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/type.rb:1063:in `retrieve_resource'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:223:in `from_resource'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:19:in `evaluate'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:174:in `apply'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:187:in `eval_resource'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:117:in `call'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:117:in `evaluate'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:327:in `thinmark'
==> VerticalServer: /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:326:in `thinmark'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:117:in `evaluate'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:118:in `traverse'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:108:in `evaluate'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:164:in `apply'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:112:in `as_logging_destination'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:163:in `apply'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:125:in `apply_catalog'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
==> VerticalServer: /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:124:in `apply_catalog'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:195:in `run'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:288:in `apply_catalog'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:228:in `main'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/context.rb:51:in `override'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet.rb:233:in `override'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:190:in `main'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application/apply.rb:151:in `run_command'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:479:in `plugin_hook'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:479:in `exit_on_fail'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:372:in `run'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/context.rb:51:in `override'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet.rb:233:in `override'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:362:in `run'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
==> VerticalServer: /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
==> VerticalServer: /usr/bin/puppet:4
```

However, if I downgrade stdlib to version 4.15.0 puppet-nvm is applied correctly without error.

Please let me know if you need any more info!

**Comment by saz** [comment]
It's working without any problems with stdlib version >= 4.25.0
