### ISSUE TITLE
nvm Warnings of deprecated methods

### ISSUE THREAD

**Issue by diegolaciar** [artberri/puppet-nvm#17]
nvm throw some warnings

My Puppetfile with the last versions

```bash
forge 'https://forge.puppet.com'

# Modules discovered by generate-puppetfile
mod 'puppetlabs/accounts', '1.3.0'
mod 'puppetlabs/ntp',      '7.1.1'
mod 'puppetlabs/stdlib',   '4.25.1'
mod 'saz/sudo',            '5.0.0'
mod 'saz/timezone',        '4.1.1'
mod 'stm/debconf',         '2.2.0'
mod 'artberri-nvm',        '1.1.1'
```

Warnings of deprecated methods

```bash
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/nvm/manifests/init.pp", 41]:["/etc/puppetlabs/code/environments/production/manifests/site.pp", 1]
   (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/nvm/manifests/init.pp", 46]:["/etc/puppetlabs/code/environments/production/manifests/site.pp", 1]
   (location: /etc/puppetlabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/production/modules/nvm/manifests/init.pp", 52]:["/etc/puppetlabs/code/environments/production/manifests/site.pp", 1]
```

**Comment by artberri** [comment]
This plugin is not maintained anymore, sorry for the inconvenience:
https://github.com/artberri/puppet-nvm?tab=readme-ov-file#deprecated-puppet-nvm
